# ----------------------------------------
# Created on: Wed Feb 19 20:24:23 2025
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "D:/modelsim/pds2022_sp6_4/usim"
vmap  adc_e2 "D:/modelsim/pds2022_sp6_4/adc_e2"
vmap  ddc_e2 "D:/modelsim/pds2022_sp6_4/ddc_e2"
vmap  dll_e2 "D:/modelsim/pds2022_sp6_4/dll_e2"
vmap  hsstlp_lane "D:/modelsim/pds2022_sp6_4/hsstlp_lane"
vmap  hsstlp_pll "D:/modelsim/pds2022_sp6_4/hsstlp_pll"
vmap  iolhr_dft "D:/modelsim/pds2022_sp6_4/iolhr_dft"
vmap  ipal_e1 "D:/modelsim/pds2022_sp6_4/ipal_e1"
vmap  ipal_e2 "D:/modelsim/pds2022_sp6_4/ipal_e2"
vmap  iserdes_e2 "D:/modelsim/pds2022_sp6_4/iserdes_e2"
vmap  oserdes_e2 "D:/modelsim/pds2022_sp6_4/oserdes_e2"
vmap  pciegen2 "D:/modelsim/pds2022_sp6_4/pciegen2"
vlog -work work   \
"D:/2L676demo/img_gamma_sim_prj/img_gamma_sim_prj/sim/img_process_tb.sv" \
"D:/2L676demo/img_gamma_sim_prj/img_gamma_sim_prj/sim/video_data_gen.sv" \
"D:/2L676demo/img_gamma_sim_prj/img_gamma_sim_prj/sim/gamma_table.v" 

# ----------------------------------------
