#Generated by Fabric Compiler ( version 2022.2-SP6.4 <build 146967> ) at Wed Feb 19 16:55:22 2025

add_simulation "D:/2L676demo/img_sim_prj/img_sim_prj/sim/img_process_tb.sv"
add_simulation "D:/2L676demo/img_sim_prj/img_sim_prj/sim/video_data_gen.sv"
add_simulation "D:/2L676demo/img_gamma_sim_prj/img_gamma_sim_prj/sim/gamma_table.v"
